spring.application.name=authenticaion

# JWT SETTING
# set private key
jwt.private-key=TEST_SYSTEM

# set issuer
jwt.issuer=PIXER-API

# set expire in (millisecons) (86400000 = 24 hours)
jwt.expire-in=86400000